spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/hsspine?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
logging:
  level:
    root: info
    org.nutz: debug
    demo: debug
management:
  security:
    enabled: false
nutz:
  json:
    enabled: true
    mode: compact
    date-format: yyyyMMdd HH:mm:ss
  dao:
    runtime:
      add-column: true
      check-index: true
      delete-column: true
      foce-create: false
      create: true
      migration: true
      basepackage: com.haha.spring.demo1
    sqlmanager:
      paths:
      - sqls
server:
  tomcat:
    uri-encoding: UTF-8